name: 发布npm
on:
  push:
    branches: [ master ]
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: 依赖安装
       run: npm install
     - name: 构建
       run: npm run build
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
     - run: ls
       env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
     


      
          
